Repository pixincreate/PixeneOS, pull requests merged in 2025-08, with the labels that each got.

#168 release.yml: Use $GRAPHENEOS_VERSION that was set in previous step
  .github/workflows/release.yml
Labels: bug

#169 docs: document possible issues and work arounds pixeneos installation from rooted-graphene
  README.md
  docs/FAQ.md
Labels: documentation

#174 chore(deps): update dependency chenxiaolong/avbroot to v3.20.0
  src/declarations.sh
Labels: dependencies

#179 chore(deps): update dependency chenxiaolong/msd to v1.15
  src/declarations.sh
Labels: dependencies
